blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RyCodeExtInc/RyCode-Ext/discussions/categories/feature-requests
      about: Share and vote on feature requests for RyCode-Ext
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline&ssr=false#review-details
      about: Enjoying RyCode-Ext? Leave a review here!
